Traceback (most recent call last):
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 631, in <module>
Traceback (most recent call last):
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 631, in <module>
Traceback (most recent call last):
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 631, in <module>
Traceback (most recent call last):
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 631, in <module>
    main()
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 621, in main
    trainer = Trainer(cfg)
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 221, in __init__
    self.init_inference_stores()
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 255, in init_inference_stores
    main()
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 621, in main
    inference_dataset = InferenceDataset(
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/datasets.py", line 53, in __init__
    trainer = Trainer(cfg)
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 221, in __init__
    self.init_inference_stores()
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 255, in init_inference_stores
    inference_dataset = InferenceDataset(
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/datasets.py", line 53, in __init__
    main()
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 621, in main
    main()
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 621, in main
    trainer = Trainer(cfg)
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 221, in __init__
    self.init_inference_stores()
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 255, in init_inference_stores
    trainer = Trainer(cfg)
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 221, in __init__
    inference_dataset = InferenceDataset(
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/datasets.py", line 53, in __init__
    self.init_inference_stores()
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/train.py", line 255, in init_inference_stores
    inference_dataset = InferenceDataset(
  File "/scratch/gpfs/GEOCLIM/LRGROUP/maximek/INMOS/samudra-bgc/src/datasets.py", line 53, in __init__
    rolling_indices = indices.rolling(
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/xarray/core/dataarray.py", line 6824, in rolling
        rolling_indices = indices.rolling(rolling_indices = indices.rolling(

  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/xarray/core/dataarray.py", line 6824, in rolling
      File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/xarray/core/dataarray.py", line 6824, in rolling
rolling_indices = indices.rolling(
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/xarray/core/dataarray.py", line 6824, in rolling
                return DataArrayRolling(self, dim, min_periods=min_periods, center=center)return DataArrayRolling(self, dim, min_periods=min_periods, center=center)return DataArrayRolling(self, dim, min_periods=min_periods, center=center)return DataArrayRolling(self, dim, min_periods=min_periods, center=center)



  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/xarray/core/rolling.py", line 259, in __init__
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/xarray/core/rolling.py", line 259, in __init__
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/xarray/core/rolling.py", line 259, in __init__
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/xarray/core/rolling.py", line 259, in __init__
                super().__init__(obj, windows, min_periods=min_periods, center=center)super().__init__(obj, windows, min_periods=min_periods, center=center)super().__init__(obj, windows, min_periods=min_periods, center=center)super().__init__(obj, windows, min_periods=min_periods, center=center)



  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/xarray/core/rolling.py", line 99, in __init__
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/xarray/core/rolling.py", line 99, in __init__
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/xarray/core/rolling.py", line 99, in __init__
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/xarray/core/rolling.py", line 99, in __init__
            raise ValueError("window must be > 0")    raise ValueError("window must be > 0")raise ValueError("window must be > 0")
raise ValueError("window must be > 0")

ValueError
ValueErrorValueError: ValueError: : window must be > 0: window must be > 0window must be > 0
window must be > 0


[2025-09-05 22:11:48,801] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 166439) of binary: /home/mk0964/.conda/envs/samudra/bin/python
Traceback (most recent call last):
  File "/home/mk0964/.conda/envs/samudra/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/mk0964/.conda/envs/samudra/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-09-05_22:11:48
  host      : tiger-i04g1
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 166440)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-09-05_22:11:48
  host      : tiger-i04g1
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 166441)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2025-09-05_22:11:48
  host      : tiger-i04g1
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 166442)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-09-05_22:11:48
  host      : tiger-i04g1
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 166439)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
